### PR TITLE
Get rid of mv command on install.sh

### PR DESCRIPTION
**Pull request by batiati**
This commit removes the `mv` command from install.sh/install.bat, implementing it in Zig instead.

Also, adds the tigerbeetle server as dependency to the Go/Java/Dotnet clients, as they need this binary in order to run the integrated tests.
As talked with @kprotty, by doing that we avoid the possibility of running the tests with an outdated version of the server.

### CODE REVIEW

**Comment by sentientwaffle** [comment]
I like that the dependency is explicit now!

I'm not sure about handling the "move" within `build.zig` though, it feels like this conflates two independent steps:
- Build the database
- "Install" the database
e.g. the difference between `make` and `make install`.

Additionally it is weird that this one binary is special cased — I would rather be uniform/consistent and build artifacts to the default output directory.

What if we leave the `mv` in the install scripts (as our "make install"), and change the clients to just point at `zig-out/bin/tigerbeetle` instead of `tigerbeetle`?

**Comment by batiati** [comment]
> What if we leave the mv in the install scripts (as our "make install"), and change the clients to just point at zig-out/bin/tigerbeetle instead of tigerbeetle?

Changing the clients to point to `/zig-out/bin` sounds good, but why do we need to keep `mv` in the install scripts?
What about having a `zig build install` for that?

**Comment by sentientwaffle** [comment]
:+1: `zig build install` works for me, I just didn't want it to be part of `build`.

Actually now I'm confused about how `zig-out` even works.. e.g.

```diff
diff --git a/build.zig b/build.zig
index 395995cc..8214f226 100644
--- a/build.zig
+++ b/build.zig
@@ -139,16 +139,19 @@ pub fn build(b: *std.build.Builder) void {
     }

     {
         const simulator = b.addExecutable("simulator", "src/simulator.zig");
         simulator.setTarget(target);
         simulator.addOptions("tigerbeetle_build_options", options);
         link_tracer_backend(simulator, tracer_backend, target);

+        const build_step = b.step("build_simulator", "Build simulator");
+        build_step.dependOn(&simulator.step);
+
         const run_cmd = simulator.run();

         if (b.args) |args| {
             run_cmd.addArgs(args);
             simulator.setBuildMode(mode);
         } else {
             simulator.setBuildMode(.ReleaseSafe);
         }
```

When  I run `build_simulator` it appears to build, but the artifact doesn't go to `zig-out`, it is hidden in the `zig-cache`.

**Comment by batiati** [comment]
> When I run `build_simulator` it appears to build, but the artifact doesn't go to `zig-out`, it is hidden in the `zig-cache`.

I suppose you have to call `simulator.install()` for that, but not sure.

**Comment by sentientwaffle** [comment]
Hmm, still in the zig-cache — under `./zig-cache/x86_64-windows/o/` now for some reason (I'm on linux). It is a linux binary though. Oh well, I was just curious. :shrug:

**Comment by batiati** [comment]
I think this directory [was created here](https://github.com/tigerbeetledb/tigerbeetle/blob/cd3209932e9b94c860d0ef5336809f4d6803dbab/build.zig#L463-L471)

I'll investigate if it's been called in the wrong place... somehow the last cache path set is being used to process other build steps.

**Comment by sentientwaffle** [comment]
See also: https://github.com/tigerbeetledb/tigerbeetle/pull/363/files

**Comment by batiati** [comment]
Last update:

- `zig build` only builds the database.
- `zig build install` builds and moves the executable to the root folder.
- `zig build go_client | java_client | dotnet_client` also builds the database as dependency, but doesn't move it.
- Clients point to `zig-out\bin` for running the server during integration tests.
- Removed `zig-cache` workaround code that was required for referencing tigerbeetle as a package (from the days we had separate repositories). It's not necessary anymore since #320 has unified the build.
- Removed `mv ./zig-out/bin/tigerbeetle .` from all scripts, in favor of `zig build install`.

**Review by sentientwaffle — APPROVED** [review]

**Pull request merged**
