### PR TITLE
Add docs build check

### PR DESCRIPTION
**Pull request by eatonphil**
Example of this catching an error:
image

https://github.com/tigerbeetledb/tigerbeetle/actions/runs/3380444969/jobs/5613237936

### CODE REVIEW

**Review by sentientwaffle — APPROVED** [review]
LGTM. Does ubuntu just have nodejs installed by default?

**Comment by eatonphil** [comment]
To make things easier for devs they install just about every major language and package manager.

**Comment by eatonphil** [comment]
I mean, Github Actions's ubuntu image does. That is not what the stock ubuntu docker image does.

**Comment by sentientwaffle** [comment]
Aha, that makes sense, thank you.

**Pull request merged**
