### PR TITLE
Fix go client build

### PR DESCRIPTION
**Pull request by jamii**
## Pre-merge checklist

Performance:

* [ ] Compare `zig benchmark` on linux before and after this pr.
    ``` sh
    # benchmark results before
    ...
    
    # benchmark results after
    ...
    ```
OR
* [x] I am very sure this PR could not affect performance.

### CODE REVIEW

**Comment by matklad** [comment]
Context

https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache

Seems update of this action broke our go builds. 


bors r+

**Comment by jamii** [comment]
> Cache not found for input keys: go-binaries-f3d96d93c2e8bd64073b536fb770aa77e348fc4d, go-binaries-f3d96d93c2e8bd64073b536fb770aa77e348fc4d

**Comment by jamii** [comment]
bors retry

**Comment by jamii** [comment]
Well now I don't see clients/go in the list at all.

bors cancel

**Pull request closed without merging**
