### PR TITLE
Tools/docker: tini

### PR DESCRIPTION
**Pull request by sentientwaffle**
Docker's default stop-signal is SIGTERM.
TigerBeetle does not have signal handlers, so "docker stop ..." with SIGINT hangs for several seconds. Setting the signal to SIGKILL instead ensures that "docker stop" doesn't delay.

This is a partial fix for https://github.com/tigerbeetle/tigerbeetle/issues/136. (The more complete fix would be adding a `SIGTERM` signal handler.)

### CODE REVIEW

**Comment by matklad** [comment]
Hm, if we _don't_ have signal handlers, shouldn't SIGTERM kill us outright?

**Comment by sentientwaffle** [comment]
Ok, this is more complicated than I expected!
If you send `SIGTERM` to a non-docker tigerbeetle replica, it _does_ exit immediately (as anticipated). 

The pause seems to be a common docker issue:

- https://github.com/docker-library/postgres/issues/184
- https://github.com/docker-library/redis/issues/386

Possible explanation is that in docker, the replica is PID 1, which has special behavior around signals: https://github.com/rustdesk/rustdesk-server/issues/36#issuecomment-1159504574

**Comment by matklad** [comment]
How idiomatic it is to _not_ run as pid1 in Docker? I've read somewhere a very reasonable argument that one should have a proper pid1 in Docker, but I am not sure if that's something people actually do?

**Comment by cb22** [comment]
> How idiomatic it is to _not_ run as pid1 in Docker? I've read somewhere a very reasonable argument that one should have a proper pid1 in Docker, but I am not sure if that's something people actually do?

It's quite idiomatic. Last I looked, it was even recommend for eg Node, and they bundle Tini - a small init system for this in later Docker releases.

**Comment by matklad** [comment]
Yeah, let's maybe do the same then? I am sure there's more weirdness to pid1

**Comment by sentientwaffle** [comment]
~Ok, this ends up being a documentation update.~

There are a couple ways tini can be used:
1. `docker run --init ...` (and an equivalent config for docker-compose).
2. Install it into the container.

~Number 2 ends up being surprisingly complicated and finicky (...alpine), so I went with 1.~

Nevermind, 1 works, it was just a DNS issue with my local docker.

**Comment by sentientwaffle** [comment]
Alpine version bump is not related, but may as well keep it fresh!

**Review by cb22 — APPROVED** [review]
Agreed that (2) is better in any case! Older versions of Docker won't have `--init`, etc.

**Pull request merged**
