### PR TITLE
LSM/SetAssociativeCache: Ease clocks alignment to shrink lower-bound size

### PR DESCRIPTION
**Pull request by sentientwaffle**
Ease clock hand alignment restrictions to:
- Shrink cache lower-bound.
- Allow more granular tuning of the cache size.

Each clock hand is (still) guaranteed (by `comptime` asserts) to not span multiple cache lines.
But in order to shrink the lower-bound cache size, remove the requirement that `clocks` itself is a multiple of the cache line size.

Old `value_count_max_multiple`:
- Grid cache: 512 values.
- Object caches: 2048 values.

New `value_count_max_multiple`:
- Grid cache: 64 values.
- Object caches: 256 values.

64 values is a minimum grid cache size of 32MiB, down from 256MiB.

### CODE REVIEW

**Comment by cb22** [comment]
LGTM - putting it through the cache map fuzz for a bit too.

**Review by cb22 — APPROVED** [review]

**Comment by matklad** [comment]
We merged zig 0.13, so this might want a rebase to unbreak the fuzzer

**Comment by cb22** [comment]
> so this might want a rebase to unbreak the fuzzer

Is the fuzzer broken? :thinking: The GH rebased it automatically / I tested with the cache map fuzz locally manually rebased and it seemed ok.

**Comment by cb22** [comment]
Ah or do you mean those seeds that were showing up for this on devhub?

**Comment by sentientwaffle** [comment]
I'm guessing CFO doesn't rebase automatically, so it was trying to run the 0.11 code with zig 0.13?

**Comment by matklad** [comment]
> I'm guessing CFO doesn't rebase automatically, so it was trying to run the 0.11 code with zig 0.13?


this: cfo doesn’t rebase, and it uses the same zig version for all fuzzing

**Pull request merged**
