### PR TITLE
move demos out of / and make them compile

### PR DESCRIPTION
**Pull request by matklad**
Will add this to CI in a separate PR

### CODE REVIEW

**Comment by eatonphil** [comment]
Maybe I'm missing it but does this also check that they compile in Github CI?

**Comment by matklad** [comment]
As per PR description, I want to add this to CI in a follow up, as those are somewhat orthogonal :P

**Comment by eatonphil** [comment]
Oops, I checked the files, not the PR description.

**Comment by matklad** [comment]
lol, guess I need to pick another branch name

>Cloning into 'tb_tmp'...
>fatal: 'demos' could be both a local file and a tracking branch.

**Comment by matklad** [comment]
Always read the source before the docs, yeah :D

**Comment by matklad** [comment]
https://github.com/tigerbeetledb/tigerbeetle/pull/380

**Pull request closed without merging**
