### PR TITLE
Explicitly fail the pipeline if a dependency fails

### PR DESCRIPTION
**Pull request by cb22**

### CODE REVIEW

**Review by matklad — DISMISSED** [review]
:see_no_evil:

**Comment by eatonphil** [comment]
I guess I missed a conversation. Why are we commenting out most of linux.yml? When will this setExecCmd be fixed?

**Comment by cb22** [comment]
Ah sorry - we're commenting out the kcov coverage in CI for now; it seems `setExecCmd` is broken, so we can't run our compiled test binary easily under `kcov` for now (I should probably dig into it a bit more, but tried executing it unconditionally, with a broken cmd, etc and there was no change)

**Comment by eatonphil** [comment]
Is it worth it to only disable the coverage checks within the test_on_bunutu step or it doesn't matter for now since this is only one of these sorts of tests anyway?

**Comment by matklad** [comment]
>I should probably dig into it a bit more,

5s glance at Zig sources tells me that it's probably fine, and that the problem is maybe elsewhere...

**Comment by cb22** [comment]
I don't quite follow?

**Comment by matklad** [comment]
I mean, nothing seems obviously broken with `setExecCmd` internally, so I have a high prior that it works, and something's broken elsewhere.

**Comment by cb22** [comment]
> I mean, nothing seems obviously broken with setExecCmd internally, so I have a high prior that it works, and something's broken elsewhere.

Oh oops, my comment was @eatonphil - I didn't see yours before replying!

**Comment by eatonphil** [comment]
Nevermind. :)

**Review by eatonphil — APPROVED** [review]

**Comment by eatonphil** [comment]
Maybe open an issue to add back code coverage?

**Pull request merged**
