### PR TITLE
Use the c implementation of blake3

### PR DESCRIPTION
**Pull request by jamii**
See https://github.com/tigerbeetledb/tigerbeetle/issues/324#issuecomment-1464621015.

We get a 17% throughput boost and blake3 goes from ~33% of runtime to ~14%. The question is whether we want to deal with having a small c dependency. Certainly, cross-platform builds might become more complicated.

In https://github.com/tigerbeetledb/tigerbeetle/commit/1abd41ffccd01944f0b2bb6f37ed6c33f5c98de6 I tried copying the zig implementation and disabling runtime safety anywhere, in case the difference was just bounds-checking. This had no noticeable effect.

## Pre-merge checklist

Performance:

* [x] Compare `zig benchmark` on linux before and after this pr.
``` sh
# benchmark results before
1223 batches in 107.08 s
load offered = 1000000 tx/s
load accepted = 93391 tx/s
batch latency p00 = 5 ms
batch latency p10 = 31 ms
batch latency p20 = 32 ms
batch latency p30 = 32 ms
batch latency p40 = 36 ms
batch latency p50 = 37 ms
batch latency p60 = 37 ms
batch latency p70 = 37 ms
batch latency p80 = 37 ms
batch latency p90 = 42 ms
batch latency p100 = 4889 ms
transfer latency p00 = 5 ms
transfer latency p10 = 3499 ms
transfer latency p20 = 9987 ms
transfer latency p30 = 17466 ms
transfer latency p40 = 25862 ms
transfer latency p50 = 36263 ms
transfer latency p60 = 48690 ms
transfer latency p70 = 60384 ms
transfer latency p80 = 73001 ms
transfer latency p90 = 85980 ms
transfer latency p100 = 97044 ms
    
# benchmark results after
load offered = 1000000 tx/s
load accepted = 109809 tx/s
batch latency p00 = 5 ms
batch latency p10 = 31 ms
batch latency p20 = 31 ms
batch latency p30 = 31 ms
batch latency p40 = 31 ms
batch latency p50 = 31 ms
batch latency p60 = 31 ms
batch latency p70 = 32 ms
batch latency p80 = 36 ms
batch latency p90 = 36 ms
batch latency p100 = 3393 ms
transfer latency p00 = 5 ms
transfer latency p10 = 3214 ms
transfer latency p20 = 9354 ms
transfer latency p30 = 15894 ms
transfer latency p40 = 23340 ms
transfer latency p50 = 32597 ms
transfer latency p60 = 42940 ms
transfer latency p70 = 52574 ms
transfer latency p80 = 63298 ms
transfer latency p90 = 73050 ms
transfer latency p100 = 81034 ms
```
OR
* [ ] I am very sure this PR could not affect performance.

### CODE REVIEW

**Comment by jamii** [comment]
I won't bother fixing all the various builds unless we decide that we want to go for it.

**Comment by jorangreef** [comment]
Let's stick with Zig's BLAKE3 for now, and first try to get it fixed upstream.

**Comment by jorangreef** [comment]
If we can't get it fixed upstream for some reason, then we can come back to whether we want to use the C implementation.

**Comment by cb22** [comment]
We've switched to using AEGIS for hashing, so closing this for now.

**Pull request closed without merging**
