### PR TITLE
cli: tone down constants.verify warning

### PR DESCRIPTION
**Pull request by matklad**
We intentionally run our releases with verification on

### CODE REVIEW

**Comment by matklad** [comment]
Added a second commit which just gets us rid of non-production build mode!

**Review by cb22 — APPROVED** [review]
> Added a second commit which just gets us rid of non-production build mode!

I think we should go one further, and remove `-Dconfig=...` :smile: but LGTM!

**Comment by matklad** [comment]
>I think we should go one further, and remove -Dconfig=... 😄 but LGTM!

Huh,but I think we could, let me tackle this!

**Comment by matklad** [comment]
https://github.com/tigerbeetle/tigerbeetle/pull/2292

**Pull request merged**
