### PR TITLE
build: add -Denforce-no-changes option

### PR DESCRIPTION
**Pull request by marler8997**
This option modifies the behavior of the build to enforce that any generated files committed to the repo are not changed.

This is another idea to catch bad commits that failed to update generated files committed to the repo (orignal idea: https://github.com/tigerbeetle/tigerbeetle/pull/2048).  The difference is that this one doesn't rely on git.  Instead, this one adds the option `-Denforce-no-changes` to `build.zig` to have it verify any generated files are already up-to-date instead of generating them.

Note that both solutions could also be used together.  This solution works without depending on git but also won't catch as many errors.  The git solution will catch any and all possible violations but also only works post commit.  I'd advocate for having both checks in place.

### CODE REVIEW

**Comment by marler8997** [comment]
With this change, here's what a CI failure would look like if you forgot to update the generated header files:

https://github.com/tigerbeetle/tigerbeetle/actions/runs/9684269284/job/26721620818?pr=2052

image

**Comment by matklad** [comment]
I like this approach! It should be easy to extend to our other genreated files, like dotnet_bindings and such. 

But I would suggest one change --- instead of a specific `-D` flag, that needs to be explicitly passed, lets look for a `CI` env variable. I find it a generally useful pattern to hide some checks behind "is_ci", and it helps when you don't need to specify this flag explicitly everywhere.

**Comment by marler8997** [comment]
That's a great idea.  Looks like GitHub actions will set `CI=true`, so I've updated the PR to check for this and set this option to `true` when it's present.  Now we don't need to modify any of the `yml` files so I've removed those changes as well.

**Comment by matklad** [comment]
LGTM, thanks!

**Review by matklad — APPROVED** [review]

**Pull request merged**
