### PR TITLE
Add docker-compose docs

### PR DESCRIPTION
**Pull request by eatonphil**
Pulling in @lewisdaly 's example from https://github.com/tigerbeetledb/tigerbeetle/issues/74.

A couple differences:

* Use ghcr.io image instead of local one (this is easier for non-devs, since they don't need to build the image locally)
* Drop the ports section (docker-compose fails since this conflicts with network-mode: host)

image

### CODE REVIEW

**Comment by lewisdaly** [comment]
Nice! I didn't know there was an existing image I could use - I ended up building my own on top of alpine.

I've also got a separate docker compose file for doing the provisioning that takes advantage of docker-compose overrides:

```yaml
version: "3.7"

# A docker-compose override to format the replica first
services:
  tigerbeetle_0:
    command: "sh -c './tigerbeetle format --cluster=0 --replica=0 0_0.tigerbeetle'"
  
  tigerbeetle_1:
    command: "sh -c './tigerbeetle format --cluster=0 --replica=1 0_1.tigerbeetle'"
  
  tigerbeetle_2:
    command: "sh -c './tigerbeetle format --cluster=0 --replica=2 0_2.tigerbeetle'"

```

Which you can run beforehand with:
```
docker-compose -f docker-compose.yml -f docker-compose.format.yml up
```

I'm not sure if that's useful at all to you - but I thought I might as well pass it along!

**Comment by eatonphil** [comment]
Thanks! Do you think there's a benefit to having format be in a docker compose file though?

It just seems more verbose (like 12 lines of docker-compose.yml + docker-compose -f, compared to the 3 lines of docker run) to me.

**Comment by lewisdaly** [comment]
No, not necessarily. I just thought I'd provide a bit more context. I quite like your approach with `docker run ...`On 6 Sept 2022 11:08 pm, Phil Eaton ***@***.***> wrote:
Thanks! Do you think there's a benefit to having format be in a docker compose file though?
It just seems more verbose (like 12 lines of docker-compose.yml + docker-compose -f, compared to the 3 lines of docker run) to me.

**Review by sentientwaffle — APPROVED** [review]

**Comment by eatonphil** [comment]
Thanks @sentientwaffle !

**Pull request merged**
