### PR TITLE
Fix CI benchmark client args

### PR DESCRIPTION
**Pull request by cb22**

### CODE REVIEW

**Review by matklad — DISMISSED** [review]

**Comment by matklad** [comment]
actually maybe rename the other way around and change the flag name? `--statsd` looks nicer

**Comment by matklad** [comment]
ping @cb22

**Comment by cb22** [comment]
@matklad sorry, with the self-assign I thought you wanted to do something here :smile: sounds good to me, will do.

**Comment by matklad** [comment]
We _assign_ reviewers so that review notfications are level-triggered.

**Comment by cb22** [comment]
@matklad for context behind the latest commit, @jorangreef and I discussed it would be best to disable the CI benchmark / associated AWS infra for now, until we make it more usable and tie it in better!

**Review by matklad — APPROVED** [review]

**Pull request merged**
