### PR TITLE
LSM: Use quicksort over `std.sort.sort` in `TableMutable`.

### PR DESCRIPTION
**Pull request by kprotty**
This nets a small win on throughput for #550 

## Pre-merge checklist

Performance:

* [x] Compare `zig benchmark` on linux before and after this pr.
    ``` sh
    # benchmark results before
    1223 batches in 135.66 s
    load offered = 1000000 tx/s
    load accepted = 73711 tx/s
    batch latency p00 = 1 ms
    batch latency p10 = 27 ms
    batch latency p20 = 29 ms
    batch latency p30 = 30 ms
    batch latency p40 = 30 ms
    batch latency p50 = 31 ms
    batch latency p60 = 32 ms
    batch latency p70 = 33 ms
    batch latency p80 = 34 ms
    batch latency p90 = 35 ms
    batch latency p100 = 5510 ms
    transfer latency p00 = 1 ms
    transfer latency p10 = 4117 ms
    transfer latency p20 = 10779 ms
    transfer latency p30 = 21173 ms
    transfer latency p40 = 34424 ms
    transfer latency p50 = 49817 ms
    transfer latency p60 = 65301 ms
    transfer latency p70 = 75458 ms
    transfer latency p80 = 91227 ms
    transfer latency p90 = 106970 ms
    transfer latency p100 = 125677 ms
    
    # benchmark results after
    1223 batches in 130.35 s
    load offered = 1000000 tx/s
    load accepted = 76718 tx/s
    batch latency p00 = 0 ms
    batch latency p10 = 28 ms
    batch latency p20 = 29 ms
    batch latency p30 = 30 ms
    batch latency p40 = 30 ms
    batch latency p50 = 31 ms
    batch latency p60 = 32 ms
    batch latency p70 = 33 ms
    batch latency p80 = 34 ms
    batch latency p90 = 35 ms
    batch latency p100 = 5481 ms
    transfer latency p00 = 0 ms
    transfer latency p10 = 3588 ms
    transfer latency p20 = 9906 ms
    transfer latency p30 = 19792 ms
    transfer latency p40 = 32453 ms
    transfer latency p50 = 47256 ms
    transfer latency p60 = 62164 ms
    transfer latency p70 = 71835 ms
    transfer latency p80 = 87100 ms
    transfer latency p90 = 102369 ms
    transfer latency p100 = 120360 ms
    ```

### CODE REVIEW

**Comment by jamii** [comment]
Solid perf improvement.

Could you add a test for the new sort? Generate some random lists, with duplicates, and check that quick_sort and std.sort.sort both produce the same result.

**Comment by jamii** [comment]
It looks like std.sort.sort does extra work to preserve ordering. Could we get any extra gains from inlining their code and removing the order arrays? Or is wikisort not actually faster for our workload for some reason?

**Comment by kprotty** [comment]
Ill add some tests and try to see if `std.sort` internals can be used. My hypothesis is the cache pollution from block sort and large buffer used when TableMutable Values are pretty large (16 - 128 bytes).

**Comment by jamii** [comment]
> cache pollution

That makes sense.

**Comment by kprotty** [comment]
Getting superseded by amortizing sorting and sorting with Keys instead of Values instead.

**Pull request closed without merging**
