### PR TITLE
sm: make pending timeouts optional 

### LINKED ISSUE #253: StateMachine: Remove pending transfer timeout≠0 constraint
## Background

In the context of a switch, TigerBeetle may need to coordinate with multiple other ledgers. To avoid undermining guarantees given to other ledgers, we should not require pending transfers to time out.

As a bonus, this means I don't have to worry about whether "timeout" is supposed to be "time_out" when used as a verb in the error code.

## Tasks

- [ ] Allow pending transfers to set `timeout = 0`.
- [ ] Remove `pending_transfer_must_timeout`.
- [ ] Update tests accordingly.
- [ ] Update documentation in `transfers.md` (the `timeout` field constraint), `create_transfers.md` (the error code).
- [ ] Update client implementations.

### PR DESCRIPTION
**Pull request by matklad**
Originally, we required pending transfers to always specify a timeout,
to ensure that the funds are always unlocked eventually.

However, if the other party we are talking to is very reliable (eg, we
are talking to another tigerbeetle), we can trust them to post or void
eventually, and having a timeout might undermine the systems'
consistency guarantees

closes https://github.com/tigerbeetledb/tigerbeetle/issues/253

### CODE REVIEW

**Comment by matklad** [comment]
waits for https://github.com/tigerbeetledb/tigerbeetle/pull/249 to be posted

**Comment by matklad** [comment]
Ready for review @sentientwaffle !

Sorry for letting it hand way to long

**Review by sentientwaffle — COMMENTED** [review]
Looks pretty good!

Just a few changes:

- Remove `pending_transfer_must_timeout` from `src/clients/node/src/index.ts`.
- Bump the `version` in `src/clients/node/package.json`.
- Remove `pending_transfer_must_timeout` from `docs/reference/operations/create_transfers.md`.
- To fix the go client test:
  - Update `src/clients/go/pkg/types/createtransferresult_string.go` (which is not currently autogenerated — I opened an [issue](https://github.com/tigerbeetledb/tigerbeetle/issues/349)).
  - Then use `scripts/format_and_codegen.sh` to regenerate the result types.

**Review by sentientwaffle — APPROVED** [review]
Thanks, this looks great!

**Pull request merged**
