### PR TITLE
Node Client: Optional build target for postinstall script.

### PR DESCRIPTION
**Pull request by A-Mozeak**
Hi there 👋🏾 

I made this change after trying to run the steps in https://github.com/interledger/rafiki/blob/main/README.md#environment-setup. (I'm on a 2019 Intel MacBook Pro, running MacOS 13.0.1 Ventura).

I was getting the following error when trying to `pnpm install` that package, and the same when `npm install`-ing in the node client in this package (on the `npm run build_lib` step of `"postinstall"`). 
```
thread 7274527 panic: Darwin is handled separately via std.zig.system.darwin module
```

I found [this solution](https://github.com/ziglang/zig/issues/10478#issuecomment-1294313967) in Zig's repo, and then made the following changes (let me know if there is a better way to do this):
1) Extract the commands from the `build_lib` script in `src/clients/node/package.json` into their own shell script.
2) Conditionally set the `-target` flag for the `zig/zig build-lib` command in that script based on a passed-in `$ZIG_BUILD_TARGET` environment variable.

Now the install commands work for me by running, e.g.:
```
ZIG_BUILD_TARGET=native-macos.11 npm i
```

I ran into a different error when trying to set the version of Zig to 0.10.0 in `src/tigerbeetle/scripts/install_zig.sh`, so I didn't go too deep into that approach. Hope this is useful!

### CODE REVIEW

**Comment by eatonphil** [comment]
If this is a fix for supporting Ventura, that sounds great! This [issue has been reported](https://github.com/tigerbeetledb/tigerbeetle-node/issues/43) before but we didn't have a solution.

**Comment by A-Mozeak** [comment]
@eatonphil it is! Any way I can help get the CI to pass?

**Comment by cb22** [comment]
Hey @A-Mozeak! 

The `clients/node` Alpine CI failure is from a change with how `npm` handles symlinks when packaging in v9 (it no longer follows them). We might just pin it to v8 as a temporary workaround until we have a better solution - any suggestions would be welcome!

**Comment by sentientwaffle** [comment]
The shellcheck failure is real — `$(node --version)` should be double-quoted. (If it returned a space, and there aren't double quotes, then it would split the argument in two).

**Comment by sentientwaffle** [comment]
bors r-

Broken in CI.

**Comment by eatonphil** [comment]
I'm not running Ventura but I do have an M1 macbook so I tried:

```
ZIG_BUILD_TARGET=native-macos.11 npm i
```

And it works for me. So I'm happy to approve.

**Comment by eatonphil** [comment]
heh, this is also failing on the validate docs step because it's from a fork. That's not a real failure but @cb22 is working on the fix.

**Comment by eatonphil** [comment]
Ok the other reason this was failing was because files that need to be included in the package must be included in the `files` section of `package.json`. Thanks Fed!

**Comment by A-Mozeak** [comment]
> heh, this is also failing on the validate docs step because it's from a fork. That's not a real failure but @cb22 is working on the fix.

I thought that might be the issue there :)

**Comment by eatonphil** [comment]
Just a heads up @A-Mozeak instead of requiring an env variable the approach I've committed detects the macos version and switches to the target you identified instead. So just a slight variation of your approach that doesn't require the user to specify anything.

**Comment by mkurapov** [comment]
Thank you for the fix! Does the package version need to bumped as well here - or does that happen in a separate process?

**Comment by eatonphil** [comment]
That's a great question. I wonder @cb22 why CI didn't complain about us not bumping version here? I think we did probably need to.

Maybe it was because we were editing non-source files.

**Comment by sentientwaffle** [comment]
I think that check was disabled b/c it was so noisy. :sweat:

**Comment by eatonphil** [comment]
PR https://github.com/tigerbeetledb/tigerbeetle/pull/430

**Comment by A-Mozeak** [comment]
Sorry I've been bogged down with other work recently and haven't had a moment to check back on this.

> Just a heads up @A-Mozeak instead of requiring an env variable the approach I've committed detects the macos version and switches to the target you identified instead. So just a slight variation of your approach that doesn't require the user to specify anything.

Sounds great, thanks for the merge!

**Comment by eatonphil** [comment]
Hey @A-Mozeak since someone is seeing the same error even with this merged I wanted to confirm that this did actually fix it for you?

**Pull request merged**
