### PR TITLE
 REPL: Control-C behavior

### PR DESCRIPTION
**Pull request by alxgh**
https://github.com/tigerbeetle/tigerbeetle/issues/1186

Handles Ctrl-C so it won't stops the client, only terminates the current prompt and opens a new one.

It is also possible to handle two consecutive Ctrl-C without typing in between but right now Ctrl-D does the work and I think that's fine :-)

NOTE: The part related to `windows` is not tested.

### CODE REVIEW

**Comment by matklad** [comment]
Thanks for the PR @alxgh!

I am wondering, do we have reference which explains the correct UNIX way to handle this? Signals are tricky! I _think_ what we do here, printing to stdout, is actually signal safe (as Zig doesn't have a lock around stdout), but it seems like it doesn't behave quite like we want it to? This is what I get with the PR applied, if I `^C` after I hit `Enter` in the middle of the command:


```
λ ./tigerbeetle client --cluster=1 --addresses=3000
TigerBeetle CLI Client 0.14.157-20-gb84d25f2
  Hit enter after a semicolon to run a command.

Examples:
  create_accounts id=1 code=10 ledger=700,
                  id=2 code=10 ledger=700;
  create_transfers id=1 debit_account_id=1 credit_account_id=2 amount=10 ledger=700 code=10;
  lookup_accounts id=1;
  lookup_accounts id=1, id=2;

> invalid command

^C
> ;
Fail near line 1, column 0:

invalid command
^ Near here.

Operation must be help, create_accounts, lookup_accounts,
create_transfers, or lookup_transfers. Got: 'invalid'.
```

See how the input is not cleared --- 'invalid command' still gets to repl, even though ^C was supposed to clear it. 

I am not sure what's the right pattern to handle this though.

**Comment by alxgh** [comment]
@matklad I think i got that bug fixed, the problem was when you hit enter it reads the input but and stores it so ctrl-c has no effect. I re-wrote the code so now it reads byte-by-byte and in case of ctrl-c clearing out the input.

I just had to use a global variable to handle the scenario which I don't know if it is acceptable or not but couldn't find a way to pass the Repl struct pointer to signal handler.

Also didn't find another way for handling this aside using signal handlers.

**Comment by alxgh** [comment]
Also no idea how to test it by code :-)

**Comment by cb22** [comment]
The REPL has this now!

**Pull request closed without merging**
