### PR TITLE
WIP tracing

### PR DESCRIPTION
**Pull request by jamii**
Here is a proposed api.

The intent is to have multiple backends, configured at compile time:
* noop
* std.log with timestamps for dependency-free debugging
* buffered write to json file to feed into eg https://gravitymoth.com/spall/spall.html
* later on, whatever metrics service we end up using in the cloud

### CODE REVIEW

**Comment by jamii** [comment]
The `pause` function is not well named. `suspend` feels better to me, but that's a keyword. Maybe even `pop` would be fine.

**Comment by jamii** [comment]
@kprotty Is this the right way to integrate with the IO system?

I'm imagining that for the json backend, Stack would be something like [16]EventAndTimestamps.

**Comment by sentientwaffle** [comment]
I'm not sure that I understand the API.

```
//!     // good
//!     Tracer.begin(event1);
//!     Tracer.begin(event2);
//!     Tracer.end(event2);
//!     Tracer.end(event1);
//!
//!     // bad
//!     Tracer.begin(event1);
//!     Tracer.begin(event2);
//!     Tracer.end(event1);
//!     Tracer.end(event2);
```

How does this work if there are multiple concurrent callers setting up / tearing down traces?

**Comment by sentientwaffle** [comment]
To integrate with `Storage`, maybe there could be a `StorageTracer(Storage)` type which implements a storage interface, but wraps the underlying storage? That way we could use it for the `test/storage.zig` `Storage` too.

**Comment by jamii** [comment]
> How does this work if there are multiple concurrent callers setting up / tearing down traces?

Take a look at the changes to io/linux.zig. The trace stack is copied into the Completion and restored when the callback is run. If you're doing stuff linearly, like most of our state machines, you can just pretend that it's sync. If you have actual concurrent children, then you have to do the `pause` pattern from the comment at the start of the module.

**Comment by jamii** [comment]
Also the `pause` is only required for making an event that spans the first IO action. If we instead started concurrent stuff in a separate callback we could get rid of `pause`:

``` zig
fn start_thing() void {
    Tracer.begin(event);
    io.on_next_tick(start_thing_a);
    io.on_next_tick(start_thing_b);
}

fn start_thing_a() void {
    Tracer.begin(event_a);
    do_thing_a(finish_thing_a);
}

fn finish_thing_a() void {
    Tracer.end(event_a);
    finish_thing();
}

fn start_thing_b() void {
    Tracer.begin(event_b);
    do_thing_b(finish_thing_b);
}

fn finish_thing_b() void {
    Tracer.end(event_b);
    finish_thing();
}

fn finish_thing() void {
    if (both_finished)
        Tracer.end(event);
}
```

**Comment by kprotty** [comment]
Can a traced event be "paused/suspended" multiple times?

**Comment by jamii** [comment]
> Can a traced event be "paused/suspended" multiple times?

The fact that it's hard to write this answer really makes me think that it's poorly named :D.

We want to put an event on the stack so that it gets copied into the Completion, and then take the event off the stack before setting up the next Completion but without recording the event as ended. 

The pause-less example above is much easier to explain, but there's a non-zero perf and complexity cost to callbackifying more code. 

Would the pause example make more sense like this?

``` zig
{
    const branch = Tracer.start_branch();
    defer Tracer.end_branch();
    Tracer.begin(event_a);
    do_thing_a();
}
{
    const branch = Tracer.start_branch();
    defer Tracer.end_branch();
    Tracer.begin(event_b);
    do_thing_b();
}
```

Same impl - just popping the stack in end_branch. But maybe easier to read?

**Comment by jamii** [comment]
Or maybe:

``` zig
const fork = Tracer.start_fork();
{
    Tracer.begin(event_a);
    do_thing_a();
    Tracer.return_to_fork(fork);
}
{
    Tracer.begin(event_b);
    do_thing_b();
    Tracer.return_to_fork(fork);
}
```

**Comment by jamii** [comment]
A real example:

``` zig
fn JoinType(comptime join_op: JoinOp) type {
    return struct {
        pub fn start(forest: *Forest, callback: Callback) void {
            assert(forest.join_op == null);
            assert(forest.join_pending == 0);
            assert(forest.join_callback == null);

            forest.join_op = join_op;
            forest.join_pending = std.meta.fields(Grooves).len;
            forest.join_callback = callback;
        }

        fn GrooveFor(comptime groove_field_name: []const u8) type {
            return @TypeOf(@field(@as(Grooves, undefined), groove_field_name));
        }

        pub fn groove_callback(
            comptime groove_field_name: []const u8,
        ) fn (*GrooveFor(groove_field_name)) void {
            return struct {
                fn groove_cb(groove: *GrooveFor(groove_field_name)) void {
                    const grooves = @fieldParentPtr(Grooves, groove_field_name, groove);
                    const forest = @fieldParentPtr(Forest, "grooves", grooves);

                    assert(forest.join_op == join_op);
                    assert(forest.join_callback != null);
                    assert(forest.join_pending <= std.meta.fields(Grooves).len);

                    Tracer.end(.{ .join_field = .{ .join_op = .open, .field_name = field.name } });

                    forest.join_pending -= 1;
                    if (forest.join_pending > 0) return;

                    Tracer.end(.{ .join = .{ .join_op = join_op } });

                    const callback = forest.join_callback.?;
                    forest.join_op = null;
                    forest.join_callback = null;
                    callback(forest);
                }
            }.groove_cb;
        }
    };
}

pub fn open(forest: *Forest, callback: Callback) void {
    const join_event = .{ .join = .{ .join_op = join_op } };
    Tracer.start(join_event);
    defer Tracer.end_later(join_event);

    const Join = JoinType(.open);
    Join.start(forest, callback);

    inline for (std.meta.fields(Grooves)) |field| {
        const join_field_event = .{ .join_field = .{ .join_op = .open, .field_name = field.name } };
        Tracer.start(join_field_event);
        defer Tracer.end_later(join_field_event);

        @field(forest.grooves, field.name).open(Join.groove_callback(field.name));
    }
}
```

**Comment by sentientwaffle** [comment]
I can't really help on the name, but the example looks good :+1:

**Comment by jamii** [comment]
I updated the docs so there are only two acceptable patterns:

``` zig
//! For events which start and finish without any async callbacks:
//!
//!     fn do_thing() {
//!         Tracer.sync_begin(event);
//!         defer Tracer.sync_end(event);
//!         ...no async io in here...
//!     }
//!
//! For events which span async callback:
//!
//!     fn start_thing() void {
//!         Tracer.async_begin(event);
//!         defer Tracer.async_end_later(event);
//!         do_some_io(finish_thing);
//!     }
//!
//!     fn finish_thing() void {
//!         do_some_more_work();
//!         Tracer.end_async(event);
//!     }
//!
//! `Tracer.sync_begin` must always be followed immediately by `defer Tracer.sync_end`.
//!
//! `Tracer.async_begin` must always be followed immediately by `defer Tracer.async_end_later`,
//! and then at some time in the future by `Tracer.async_end`.
//! This is especially important when starting multiple concurrent events:
//!
//!     fn start_thing() void {
//!         Tracer.async_begin(event);
//!         defer Tracer.async_end_later(event);
//!         {
//!             Tracer.async_begin(event_a);
//!             defer Tracer.async_end_later(event_a);
//!             do_thing_a(finish_thing_a);
//!         }
//!         {
//!             Tracer.async_begin(event_b);
//!             defer Tracer.async_end_later(event_b);
//!             do_thing_b(finish_thing_b);
//!         }
//!     }
//!
//!     fn finish_thing_a() void {
//!         Tracer.async_end(event_a);
//!         finish_thing();
//!     }
//!
//!     fn finish_thing_b() void {
//!         Tracer.async_end(event_b);
//!         finish_thing();
//!     }
//!
//!     fn finish_thing() void {
//!         if (both_finished)
//!             Tracer.async_end(event);
//!     }
```

**Comment by jamii** [comment]
I gave up on tracking the stack of events in the io system - it required that every function either always suspends or never suspends, which is a design goal in TB but not yet realized.

Reaching a static allocation api was also non-trivial because the number of possible events depends on the config we're testing (eg in tree_fuzz we use a tree_name that doesn't exist in the production code). 

The tradeoff I ended up at is that callers must pre-allocate space for currently running events, and each pre-allocated event must hardcode it's parent event. Then we assert at runtime that the starts/ends we observe obey this hardcoded hierarchy.

This requires a bit more boilerplate when adding events ([eg](https://github.com/tigerbeetledb/tigerbeetle/blob/fafdedf8bad9a1062256daa4bee78a8fc50690f5/src/lsm/tree.zig#L148-L150)), but on the other hand reduces the scope for error.

**Pull request closed without merging**
