### PR TITLE
don't mix tabs and spaces in bootstrap.sh

### PR DESCRIPTION
**Pull request by matklad**
bootstarp.sh is probably something people would look at to learn how to download tigerbeetle, it should be readable.

### CODE REVIEW

**Comment by cb22** [comment]
While you're here, can you add it to the `lint_shellcheck` too!

**Comment by matklad** [comment]
Good call, though it seems that shellcheck is fine about mixing tabs&spaces here?

**Comment by sentientwaffle** [comment]
As an aside, ignoring style preferences, there is one place where "spaces vs tabs" actually matters in shell scripts -- heredocs work better with tabs. (e.g. https://tldp.org/LDP/abs/html/here-docs.html example 19-4).

**Comment by cb22** [comment]
> though it seems that shellcheck is fine about mixing tabs&spaces here?

I was quite surprised by this too, given how opinionated they are on other things!

**Review by cb22 — APPROVED** [review]

**Pull request merged**
