### PR TITLE
No qemu for docker during pull requests

### PR DESCRIPTION
**Pull request by eatonphil**
## Pre-merge checklist

Performance:

* [ ] Compare `zig benchmark` on linux before and after this pr.
    ``` sh
    # benchmark results before
    ...
    
    # benchmark results after
    ...
    ```
OR
* [X] I am very sure this PR could not affect performance.

### CODE REVIEW

**Comment by matklad** [comment]
I think you need to remove these lines

```

      - build-and-push
      - build-and-push-debug
```

so that we don't gate on bors

**Comment by eatonphil** [comment]
>       - build-and-push
>      - build-and-push-debug

Hmm that wasn't the point of the PR though, unless I'm misunderstanding.

**Comment by matklad** [comment]
d'oh, right it is exactly the purpose of this PR to not remove these checks from bors. Confused myself here. 

This looks basically right to me, lets land! (should double-check thougs that it works as expected on main)

bors r+

**Comment by eatonphil** [comment]
Sorry I noticed when you brought up the debug version that I didn't set up the qemu skip there. Just added

**Comment by matklad** [comment]
yup, it took 20 minutes on master, so it must be working: https://github.com/tigerbeetledb/tigerbeetle/actions/runs/4087346553/jobs/7047816630

**Pull request merged**
