### PR TITLE
Remove required_approvals and stick to using bors

### PR DESCRIPTION
**Pull request by cb22**
So we can implement the workflow @matklad suggested [here](https://github.com/tigerbeetledb/tigerbeetle/pull/385#discussion_r1066932594).

### CODE REVIEW

**Comment by sentientwaffle** [comment]
bors r+

My mistake, I thought github settings changes auto-saved but I had to scroll down and click "save" :facepalm:

**Comment by sentientwaffle** [comment]
bors r+

This should pass now that https://github.com/tigerbeetledb/tigerbeetle/pull/388 is merged.

**Comment by sentientwaffle** [comment]
@batiati can you take a look at this flaky CI failure?: https://github.com/tigerbeetledb/tigerbeetle/actions/runs/3895100141/jobs/6650260999

**Comment by sentientwaffle** [comment]
bors r+

(Trying again to merge this; hopefully will have better luck with the flaky test).

**Comment by batiati** [comment]
> can you take a look at this flaky CI failure?:

I suspect it is `actions/upload-artifact@v3`'s fault, the artifact is not being restored sometimes. I'll change the CI to use `actions/cache@v3`, the same action used by the Go client CI.

**Pull request merged**
