### PR TITLE
Java client: Add support for musl-based Linux distros and fix Mac OS detection

### LINKED ISSUE #265: Java client should support alpine
This will also maybe become obvious once the Node client's tests on major distros are ported to the Java (and Go client) as well.

### PR DESCRIPTION
**Pull request by batiati**
### This PR:

- Cross-compiles for linux using glibc and musl: The JVM can only load the JNI lib that matches its libc, so we must distribute both versions inside the .jar package.

- Simplifies the cross-compilation naming process, changing the lib subdirectory's names to match the zig triple `arch-os-abi`.

- Detects musl-based distros during runtime by inspecting the process's loaded libraries.

- Minor adjustments for impacted test cases.

- Closes #265

- Also, closes https://github.com/tigerbeetledb/tigerbeetle-java/pull/21

- Tested on docker using the `openjdk:17-alpine` image.

### Not included in this PR:

- GHA to test the client in all supported platforms will be done by #284

### CODE REVIEW

**Comment by eatonphil** [comment]
Nice! I guess you'll add the actual (Github Actions) tests for this and other distros when you do https://github.com/tigerbeetledb/tigerbeetle/issues/252?

**Comment by batiati** [comment]
Yes, I'm working on that. I just made it in two PRs because I need the package with Alpine support published first.

**Comment by eatonphil** [comment]
Sounds good!

**Comment by eatonphil** [comment]
The [error you're getting](https://github.com/tigerbeetledb/tigerbeetle/actions/runs/3519311867/jobs/5899134649) I just noticed that the validate_docs.sh script does not work if the PR is on a fork. We'll need to fix that script to support checking out from a different fork...

**Comment by batiati** [comment]
Added a workaround for the required build options introduced by the tracing API.
This provisory hack will be removed once the client is built using the root `build.zig` file.

All checks, except for the unrelated "node version check"  and "validate docs", are green now.

**Review by sentientwaffle — APPROVED** [review]

**Pull request merged**
