### PR TITLE
docs: header and footer tweaks

### PR DESCRIPTION
**Pull request by emschwartz**
- **docs: rename Twitter links to 𝕏**
- **docs: use white logo for dark mode**
- **docs: make title use italics**
- **docs: add logo to footer with link to homepage**
- **docs: use single row of footer links**

### CODE REVIEW

**Review by sentientwaffle — COMMENTED** [review]
LGTM, though you need to add `img/logo-white.svg` to the `tidy.zig`'s `"tidy exceptions"` whitelist.

**Review by sentientwaffle — DISMISSED** [review]
LGTM.

Not worth the trouble, but fyi you can also recolor a single SVG logo with CSS, instead of swapping SVGs depending on the theme.

**Comment by sentientwaffle** [comment]
CI is failing; I think you need to run `zig fmt`.

**Comment by matklad** [comment]
CI failed due to tidy's own source code being untidy (longer than 100lines). I went ahead and pushed a fix to your branch emschwartz!

zig fmt handling of tabular data is nifty, albeit somewhat unintuitive --- it looks at the number of items in the first row, and then rewraps all subsequent rows to have the same numer of items. 

So, I manually added `\n` to make sure the first row is only three elements wide, then hit `zig fmt` to reflow the entire table. And then I put all svgs next to each other.

**Review by matklad — APPROVED** [review]

**Pull request merged**
